sudo: required
services:
  - docker

before_install:
  - docker build -t mattbliese/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mattbliese/react-test npm test -- --coverage

after_success:
  - docker build -t mattbliese/multi-client ./client
  - docker build -t mattbliese/multi-nginx ./nginx
  - docker build -t mattbliese/multi-server ./server
  - docker build -t mattbliese/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those imgaes and push them to docker hub
  - docker push mattbliese/multi-client
  - docker push mattbliese/multi-nginx 
  - docker push mattbliese/multi-server
  - docker push mattbliese/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker2-env'
  bucket_name: 'elasticbeanstalk-us-east-2-851625538623'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY